SWPACINFO_FINAL:= "Unisoc: $(TARGET_PRODUCT)_$(TARGET_BUILD_VARIANT)_$(TARGET_BUILD_VERSION)"

ifneq ($(SWPACINFO),)
SWPACINFO_FINAL:= $(SWPACINFO)
endif

$(warning "SWPACINFO : $(SWPACINFO_FINAL)")

$(shell mkdir -p $(TARGET_OUT_VENDOR_ETC))
$(shell bash -c 'echo "$(SWPACINFO_FINAL)" > "$(TARGET_OUT_VENDOR_ETC)/SWPACInfo.txt"')
